# Generated by Django 4.2.2 on 2023-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_img',
            field=models.ImageField(upload_to='./static/movies/cover_images'),
        ),
    ]
