# Generated by Django 4.2.2 on 2023-06-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_img',
            field=models.ImageField(upload_to='cover_images'),
        ),
    ]
