# Generated by Django 4.2.2 on 2023-06-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_watchlist_movie_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.watchlist'),
        ),
    ]
